name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Ensure the database is ready before running tests
        options: >-
          --health-cmd "pg_isready -U $${POSTGRES_USER}"
          --health-timeout 30s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.17.0

    - name: Install dependencies
      run: npm install

    - name: Set up Docker Compose
      run: docker-compose -f docker/docker-compose.yml up -d

    - name: Run database setup
      run: |
        docker-compose -f docker/docker-compose.yml exec -T postgres psql -U your_user -d your_database -f db_scripts/users.sql

    - name: Run tests
      run: npm test -- --detectOpenHandles

    - name: Tear down Docker Compose
      if: always()
      run: docker-compose -f docker/docker-compose.yml down
